- name: Install curl, sudo, and Tailscale
  gather_facts: true  # Change this to true
  vars_prompt:
    - name: api_key
      prompt: Enter Tailscale API Key
  hosts: tailscale
  become: yes
  tasks:
    - name: Install curl and sudo on Debian-based systems
      apt:
        name:
          - curl
          - sudo
        state: present
      when: ansible_os_family == "Debian"

    - name: Install curl and sudo on Arch Linux
      pacman:
        name:
          - curl
          - sudo
        state: present
      when: ansible_distribution == "Archlinux"

    - name: Install curl and sudo on RPM-based systems
      yum:
        name:
          - curl
          - sudo
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install curl and sudo on RPM-based systems (for dnf)
      dnf:
        name:
          - curl
          - sudo
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_version is version('8', '>=')

    - name: Download and install Tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh
      args:
        executable: /bin/bash

    - name: Start Tailscale with auth key
      shell: tailscale up --auth-key={{ api_key }}
      args:
        executable: /bin/bash
